"""add config column to chatbot

Revision ID: 0e678276ee70
Revises: 077e26ac44d5
Create Date: 2026-02-03 14:25:05.806477

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0e678276ee70'
down_revision = '077e26ac44d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chatbot', schema=None) as batch_op:
        batch_op.add_column(sa.Column('configuration', postgresql.JSONB(astext_type=sa.Text()), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chatbot', schema=None) as batch_op:
        batch_op.drop_column('configuration')

    # ### end Alembic commands ###
