"""Add database_name to Chatbot model

Revision ID: 523f270d10f5
Revises: 4c823588c1c9
Create Date: 2026-01-09 10:28:38.234065

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '523f270d10f5'
down_revision = '4c823588c1c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # Allow user id to be nullable
    op.alter_column('user', 'id', nullable=True)

    # Create enum type first (including 'student')
    op.execute("CREATE TYPE divisionenum AS ENUM ('student', 'staff', 'faculty')")

    # Add missing columns to chatbot table
    op.add_column('chatbot', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('chatbot', sa.Column('database_name', sa.String(length=128), nullable=True))
    op.add_column('chatbot', sa.Column('attachments', postgresql.ARRAY(sa.String(length=256)), nullable=True))
    op.add_column('chatbot', sa.Column('publish_date', sa.DateTime(), nullable=True))
    op.add_column('chatbot', sa.Column('division', sa.Enum('student', 'staff', 'faculty', name='divisionenum', create_type=False), nullable=True, server_default='student'))
    op.add_column('chatbot', sa.Column('is_active', sa.Boolean(), nullable=True, server_default='false'))
    op.add_column('chatbot', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('chatbot', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))

    # Add missing columns to user table
    op.add_column('user', sa.Column('password_hash', sa.String(length=256), nullable=True))
    op.add_column('user', sa.Column('division', sa.Enum('student', 'staff', 'faculty', name='divisionenum', create_type=False), nullable=True))
    op.add_column('user', sa.Column('is_admin', sa.Boolean(), nullable=True, server_default='true'))
    op.add_column('user', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('user', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))

    # Add missing columns to chat_session table
    op.add_column('chat_session', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('chat_session', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))

    # Add missing columns to chat_message table
    op.add_column('chat_message', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('chat_message', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))

    # Update existing chatbot rows with database names
    op.execute("UPDATE chatbot SET database_name = 'uat_buv_sio' WHERE name = 'buv'")
    op.execute("UPDATE chatbot SET database_name = 'uat_su_sio' WHERE name = 'su'")
    op.execute("UPDATE chatbot SET database_name = 'demo_uol' WHERE name = 'uol'")
    op.execute("UPDATE chatbot SET database_name = 'demo_ifp' WHERE name = 'ifp'")
    op.execute("UPDATE chatbot SET database_name = 'demo_aub' WHERE name = 'aub'")
    op.execute("UPDATE chatbot SET database_name = 'demo_us' WHERE name = 'us'")

    # Now make database_name non-nullable
    op.alter_column('chatbot', 'database_name', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop added columns from chatbot
    op.drop_column('chatbot', 'updated_at')
    op.drop_column('chatbot', 'created_at')
    op.drop_column('chatbot', 'is_active')
    op.drop_column('chatbot', 'division')
    op.drop_column('chatbot', 'publish_date')
    op.drop_column('chatbot', 'attachments')
    op.drop_column('chatbot', 'database_name')
    op.drop_column('chatbot', 'description')

    # Drop added columns from user
    op.drop_column('user', 'updated_at')
    op.drop_column('user', 'created_at')
    op.drop_column('user', 'division')
    op.drop_column('user', 'is_admin')
    op.drop_column('user', 'division')
    op.drop_column('user', 'password_hash')

    # Drop added columns from chat_session
    op.drop_column('chat_session', 'updated_at')
    op.drop_column('chat_session', 'created_at')

    # Drop added columns from chat_message
    op.drop_column('chat_message', 'updated_at')
    op.drop_column('chat_message', 'created_at')

    # Drop enum type
    op.execute('DROP TYPE IF EXISTS divisionenum CASCADE;')
    # ### end Alembic commands ###
