"""add created_at columns for chat_message and chat_session

Revision ID: 597379d39d3e
Revises: 4c823588c1c9
Create Date: 2025-05-09 19:44:16.769801

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '597379d39d3e'
down_revision = '4c823588c1c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('chat_session', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_session', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    with op.batch_alter_table('chat_message', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
