"""add source to chat_message

Revision ID: 6f887603d47a
Revises: 0e678276ee70
Create Date: 2026-02-09 16:29:39.375023

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6f887603d47a'
down_revision = '0e678276ee70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
        batch_op.drop_constraint('chat_message_referenced_document_id_fkey', type_='foreignkey')
        batch_op.drop_column('referenced_document_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('referenced_document_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('chat_message_referenced_document_id_fkey', 'document', ['referenced_document_id'], ['id'])
        batch_op.drop_column('source')

    # ### end Alembic commands ###
