"""remove chatbot unique name and size limit

Revision ID: b47fa1825eef
Revises: 6f887603d47a
Create Date: 2026-03-03 00:12:28.724845

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = 'b47fa1825eef'
down_revision = '6f887603d47a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chatbot', schema=None) as batch_op:
        batch_op.drop_constraint('chatbot_name_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chatbot', schema=None) as batch_op:
        batch_op.create_unique_constraint('chatbot_name_key', ['name'])

    # ### end Alembic commands ###
