"""add reply_to_id to chat_message

Revision ID: f8389b0332b7
Revises: df86acf4a4d2
Create Date: 2026-03-25 15:01:53.897580

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8389b0332b7'
down_revision = 'df86acf4a4d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reply_to_message_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'chat_message', ['reply_to_message_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_message', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('reply_to_message_id')

    # ### end Alembic commands ###
